// Auto-generated by the EMBLOCS block compiler.
// Do not edit this file.
// Source: integrator.bloc

#ifndef INTEGRATOR_H
#define INTEGRATOR_H

#include "emblocs_comp.h"

// define instance structure
typedef struct {
    bl_pin_float_t in_;
    bl_pin_float_t out_;
#if (HAS_ENABLE)
    bl_pin_bit_t enable_;
#endif
#if (HAS_HOLD)
    bl_pin_bit_t hold_;
#endif
    float accumulator;
} BL_MANGLE(t);

#define pIN_  (self->in_)
#define IN_  (*self->in_)
#define pOUT_  (self->out_)
#define OUT_  (*self->out_)
#if (HAS_ENABLE)
#define pENABLE_  (self->enable_)
#define ENABLE_  (*self->enable_)
#endif
#if (HAS_HOLD)
#define pHOLD_  (self->hold_)
#define HOLD_  (*self->hold_)
#endif

#endif // INTEGRATOR_H
