// Auto-generated by the EMBLOCS block compiler.
// Do not edit this file.
// Source: limit1.bloc

#ifndef LIMIT1_H
#define LIMIT1_H

#include "emblocs_comp.h"


// define instance structure
typedef struct {
    bl_pin_float_t in_;
    bl_pin_float_t min_;
    bl_pin_float_t max_;
    bl_pin_float_t out_;
} BL_MANGLE(t);

#define pIN_  (self->in_)
#define IN_  (*self->in_)
#define pMIN_  (self->min_)
#define MIN_  (*self->min_)
#define pMAX_  (self->max_)
#define MAX_  (*self->max_)
#define pOUT_  (self->out_)
#define OUT_  (*self->out_)

#endif // LIMIT1_H
