// Auto-generated by the EMBLOCS block compiler.
// Do not edit this file.
// Source: pico_gpio.bloc

#ifndef PICO_GPIO_H
#define PICO_GPIO_H

#include "emblocs_comp.h"


// define instance structure
typedef struct {
#if (INPUTS!=0)
    bl_pin_bit_t pin00_in_[30];
#endif
#if (OUTPUTS!=0)
    bl_pin_bit_t pin00_out_[30];
#endif
#if (ENABLES!=0)
    bl_pin_bit_t pin00_oe_[30];
#endif
#if (INPUTS!=0)
#endif
#if (OUTPUTS!=0)
#endif
} BL_MANGLE(t);

#if (INPUTS!=0)
#define pPIN00_IN_  (self->pin00_in_)
#define PIN00_IN_(i)  (*(self->pin00_in_[i]))
#endif
#if (OUTPUTS!=0)
#define pPIN00_OUT_  (self->pin00_out_)
#define PIN00_OUT_(i)  (*(self->pin00_out_[i]))
#endif
#if (ENABLES!=0)
#define pPIN00_OE_  (self->pin00_oe_)
#define PIN00_OE_(i)  (*(self->pin00_oe_[i]))
#endif

#endif // PICO_GPIO_H
