// Auto-generated by the EMBLOCS block compiler.
// Do not edit this file.
// Source: integrator.bloc

#ifndef INTEGRATOR_H
#define INTEGRATOR_H

#include "emblocs_comp.h"

// set default parameter values if not supplied
#ifndef HAS_ENABLE
#define HAS_ENABLE (0)
#endif
#ifndef HAS_HOLD
#define HAS_HOLD (0)
#endif

#define BL_CONCAT(a, b)  a##b
#define BL_MANGLE(name)  BL_CONCAT(BL_BLOCK_NAME, _##name)

// define instance structure
typedef struct {
    bl_pin_float_t in_;
    bl_pin_float_t out_;
#if (HAS_ENABLE)
    bl_pin_bit_t enable_;
#endif
#if (HAS_HOLD)
    bl_pin_bit_t hold_;
#endif
    float accumulator;
} BL_MANGLE(t);

#define IN_  (*self->in_)
#define OUT_  (*self->out_)
#if (HAS_ENABLE)
#define ENABLE_  (*self->enable_)
#endif
#if (HAS_HOLD)
#define HOLD_  (*self->hold_)
#endif

#endif // INTEGRATOR_H