// Auto-generated by the EMBLOCS block compiler.
// Do not edit this file.
// Source: limit1.bloc

#ifndef LIMIT1_H
#define LIMIT1_H

#include "emblocs_comp.h"

#define BL_CONCAT(a, b)  a##b
#define BL_MANGLE(name)  BL_CONCAT(BL_BLOCK_NAME, _##name)

// define instance structure
typedef struct {
    bl_pin_float_t in_;
    bl_pin_float_t min_;
    bl_pin_float_t max_;
    bl_pin_float_t out_;
} BL_MANGLE(t);

#define IN_  (*self->in_)
#define MIN_  (*self->min_)
#define MAX_  (*self->max_)
#define OUT_  (*self->out_)

#endif // LIMIT1_H