// Auto-generated by the EMBLOCS block compiler.
// Do not edit this file.
// Source: mux.bloc

#ifndef MUX_H
#define MUX_H

#include "emblocs_comp.h"

// set default parameter values if not supplied
#ifndef NUM_CHAN
#define NUM_CHAN (1)
#endif
#ifndef NUM_INPUT
#define NUM_INPUT (2)
#endif

#define BL_CONCAT(a, b)  a##b
#define BL_MANGLE(name)  BL_CONCAT(BL_BLOCK_NAME, _##name)

// define instance structure
typedef struct {
#if (NUM_CHAN==1)
    bl_pin_raw_t in0_[NUM_INPUT];
    bl_pin_raw_t out_;
#endif
#if (NUM_CHAN>1)
    bl_pin_raw_t ch00_in0_[NUM_INPUT][NUM_CHAN];
    bl_pin_raw_t ch00_out_[NUM_CHAN];
#endif
    bl_pin_u32_t select_;
} BL_MANGLE(t);

#if (NUM_CHAN==1)
#define pIN0_  (self->in0_)
#define IN0_(i)  (*(self->in0_[i]))
#define pOUT_  (self->out_)
#define OUT_  (*self->out_)
#endif
#if (NUM_CHAN>1)
#define pCH00_IN0_  (self->ch00_in0_)
#define CH00_IN0_(i, j)  (*(self->ch00_in0_[i][j]))
#define pCH00_OUT_  (self->ch00_out_)
#define CH00_OUT_(i)  (*(self->ch00_out_[i]))
#endif
#define pSELECT_  (self->select_)
#define SELECT_  (*self->select_)

#endif // MUX_H