// Auto-generated by the EMBLOCS block compiler.
// Do not edit this file.
// Source: not.bloc

#ifndef NOT_H
#define NOT_H

#include "emblocs_comp.h"


// define instance structure
typedef struct {
    bl_pin_bit_t in_;
    bl_pin_bit_t out_;
} BL_MANGLE(t);

#define pIN_  (self->in_)
#define IN_  (*self->in_)
#define pOUT_  (self->out_)
#define OUT_  (*self->out_)

#endif // NOT_H
